version: 0.0.{build}
os: Visual Studio 2015

clone_depth: 5

platform:
  - x64

configuration:
  - Release

install:
  - git submodule update --init --recursive

before_build:
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 14 2015 Win64" -DCITRA_USE_BUNDLED_QT=1 -DCITRA_USE_BUNDLED_SDL2=1 ..
  - cd ..
after_build:

- cmd: 7z a release.7z C:\projects\citra-30v4x\build\bin\*

build:
  project: build/citra.sln
  parallel: true


artifacts:

- path: release.7z

  name: release

deploy:
- provider: GitHub
  auth_token:
    secure: U0ksP/ootcmbZcebIK89O8CPgjsKAnDiFVKWA1qyqTyAAlvD/gJ7zIPiVCrppKkD
  draft: true
  prerelease: true

