version: 0.0.{build}
os: Visual Studio 2015

platform:
  - x64

configuration:
  - Release

install:
  - git submodule update --init --recursive

before_build:
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 14 2015 Win64" -DCITRA_USE_BUNDLED_GLFW=1 -DCITRA_USE_BUNDLED_QT=1 ..
  - cd ..

after_build:
    # copying the needed QT Dlls is now done post build. See the CMakeLists.txt file in the citra-qt folder
  - ps: >
        if (!"$env:APPVEYOR_PULL_REQUEST_TITLE" -and ("$env:APPVEYOR_REPO_BRANCH" -eq "master"))
          {
            $GITDATE = $(git show -s --date=short --format='%ad') -replace "-",""
            $GITREV = $(git show -s --format='%h')
            # Where are these spaces coming from? Regardless, let's remove them
            $BUILD_NAME = "citra-${GITDATE}-${GITREV}-windows-amd64.7z" -replace " ",""
            $BUILD_NAME_NOQT = "citra-noqt-${GITDATE}-${GITREV}-windows-amd64.7z" -replace " ",""
            # Zip up the build folder
            7z a $BUILD_NAME .\build\bin\release\*
            # Do a second archive with only the binaries
            7z a $BUILD_NAME_NOQT .\build\bin\release\*.exe
deploy:
- provider: GitHub
  auth_token:
    secure: U0ksP/ootcmbZcebIK89O8CPgjsKAnDiFVKWA1qyqTyAAlvD/gJ7zIPiVCrppKkD
  draft: true
  prerelease: true
 environment:
